- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- app/src/components/docGen.js
- app/src/components/validators.js
- app/src/routes/v1/docGen.js
- app/tests/unit/components/validators/validators.models.spec.js
https://apps.nrs.gov.bc.ca/int/jira/projects/SHOWCASE/issues/SHOWCASE-372
PR template for this repo blank, will be cleaning all that up as part of another ongoing ticket.
> Prevent API crash on Carbone failure

- app/src/routes/v1/health.js
> Fix health

- Jenkinsfile
- Jenkinsfile.cicd
- app/README.md
- app/src/components/docGen.js
- app/tests/unit/components/utils.spec.js
Add the capability for filenames to be templated.
Also throw in jenkinsfiles.
To execute a filename replacement, the same syntax as in the file for Carbone generation is used.
"template": {
"filename": "mx_permit_{d.permitNumber}.docx",
Will result in the response file being "mx_permit_XXXX.docx" assuming there is a permitNumber field with XXXX in the context object.
> Filename templating

- app/README.md
Used the wrong name in the readme
> Fix readme typo

- app/README.md
- app/package-lock.json
- app/package.json
- app/src/components/docGen.js
- app/src/components/utils.js
- app/src/components/validators.js
- app/src/docs/v1.api-spec.yaml
- app/tests/unit/components/utils.spec.js
- app/tests/unit/components/validators/validators.customValidators.spec.js
- app/tests/unit/components/validators/validators.models.spec.js
- app/tests/unit/components/validators/validators.validatorUtils.spec.js
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-403
API changes supporting PDF exporting. Altered `template` field in the request body to use the following 3 new fields (removed old "filename" field)
- contentFileType **required**
- outputFileType
- outputFileName
Altered validation to support these fields.
Altered API docs and readme.
New feature (non-breaking change which adds functionality) 
Documentation (non-breaking change with enhancements to documentation) 
> API changes to support PDF conversion

- openshift/app.dc.yaml
This PR explicitly adds NSP objects to the app.dc.yaml template. As this is a standalone API, no other NSPs are required aside from the K8S api.
We need to harden our security following Trust No One principles.
[[SHOWCASE-480]](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-480)
> Add custom Network Security Policies to Deployment Template

- openshift/app.dc.yaml
This PR allows the application to talk to Keycloak.
Without this change, the service will timeout and not function.
> Add missing egress NSP to allow keycloak network traffic

- app/app.js
- app/package-lock.json
- app/package.json
- app/src/components/docGen.js
- app/src/middleware/apiTracker.js
- app/src/middleware/authorizedParty.js
- openshift/app.dc.yaml
Add middleware to track docgen calls, output to log only for now.
> Api Logging Middleware

- app/package-lock.json
- app/package.json
- app/src/docs/v1.api-spec.yaml
This PR adds header content to docGen response specification as well as more verbose description fields where appropriate
This completes the original bug where the file output name was not matching the template and ensures that CDOGS is reporting the right type of metadata in the headers as part of the spec definition.
[[SHOWCASE-468]](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-468)
[[SHOWCASE-469]](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-469)
> Add Header documentation to OpenAPI YAML spec

- app/src/middleware/carboneCopy.js
Make docs and api-spec publicly accessible.  Currently everything under /v2 (where carbone-copy-api is mounted) requires authentication.
[SHOWCASE-982](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-982)
> Make v2 docs public

- app/config/custom-environment-variables.json
- app/package-lock.json
- app/package.json
- app/src/components/fileCacheUtils.js
- app/src/middleware/carboneCopy.js
- openshift/README.md
- openshift/app.dc.yaml
Ensure PVC configured for multiple pods - ReadWriteMany.
> Update PVC access mode.

- app/package-lock.json
This update to dot-prop npm package addresses a security vulnerability as reported here:
https://hackerone.com/reports/719856
> upgrade dot-prop to version 5.1.1 or later

- app/tests/postman/example.postman_environment.json
added the auth_host and cdogs_host environemnt variables to the example template.
removed some unnecessary properties generated by postman
> simplified env file

- app/package-lock.json
- app/package.json
- app/src/components/utils.js
Update carbone and carbone-copy-api to version 2.
The underlying carbone code has been updated (see [changelog](https://github.com/Ideolys/carbone/blob/master/CHANGELOG.md)).
Updates made to our wrapper (carbone-copy-api).  
Minor updates to other packages.
> Update carbone and carbone-copy-api to version 2

- app/package-lock.json
- app/package.json
- app/src/components/utils.js
This reverts commit 7fa0a3cef3ab770157ceea0f308ed024a2a18a3b, reversing
changes made to b48ecbcba733d1e39547b00b23392403ade0d718.
Need to rollback #44 
> Revert "Merge pull request #44 from parc-jason/feature/carbone-2"

- app/README.md
- app/lcov-fix.js
- app/package-lock.json
- app/package.json
- app/src/components/utils.js
This reverts commit 49881e931c67b068cf00aa6e6ee50a866439981a, reversing
changes made to 7fa0a3cef3ab770157ceea0f308ed024a2a18a3b.
A standard npm audit and dependency update was performed.
> Revert "Merge pull request #45 from jujaga/bugfix/undo-pr-44"

- openshift/OIDC-Migration.md
- openshift/README.md
- openshift/app-oidc.dc.yaml
- openshift/app.dc.yaml
- openshift/nsp.yaml
This PR adds pre-emptive OCP4 changes, and provides templates and a plan of action for SSO to OIDC auth migration.
[SHOWCASE-1684](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1684)
> Create Parallel OIDC version of CDOGS deployment

- openshift/fluent-bit.cm.yaml
this change helps achieve log message checking/alerting for logs that arent in the expected apache format.
for example, if the message is 'ERR! Error doing something..'
We can modify the format of the logs collected by the sidecar to include the full original message in a field with key 'log'.. as well as the message parsed into apache format.
> update fluent-bit config of log parsing

- app/package-lock.json
- app/package.json
- openshift/app.bc.yaml
NPM Package updates and image version bumps
Follow-up to: https://github.com/bcgov/common-services-team-library/pull/19
[SHOWCASE-2067](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2067)
> Routine Dependency Updates

- .github/workflows/unit-tests.yaml
- app/Dockerfile
- app/package-lock.json
- app/package.json
see Ticket - [Update CDOGS to Node 16 LTS](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2289)
Unit tests run in GitHub actions should pass for Node versions 12, 14 and 16.
> Update NPM Packages to support Node16 upgrade

- app/src/components/carboneCopyApi.js
- openshift/app.dc.yaml
- openshift/fluent-bit.cm.yaml
see ticket: https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2342
With this PR we can view CDOGS 'access' type logs on the AWS OpenSearch service.
These are our express (http level) logs like:
`{"azp":"DGRSC_SERVICE_CLIENT","contentLength":"16558","httpVersion":"1.1","ip":"::1","level":"http","message":"POST /api/v2/template/render 200 354ms","method":"POST","path":"/api/v2/template/render","responseTime":354,"statusCode":200,"timestamp":"2022-01-20T23:10:26.398Z","userAgent":"PostmanRuntime/7.28.4"}`
So we should at least be able to get an idea or which client is hitting the render endpoint and build a basic dashboard from that.
Kibana is available here:
https://apm.io.nrs.gov.bc.ca/_dashboards/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-7d,to:now)) …
> fluent-bit to AWS

- app/src/components/carboneRender.js
- app/src/components/validation.js
- app/src/routes/v2/render.js
- app/src/routes/v2/template.js
Updating log statements throughout to Winston JSON format that were missed in initial changeover.
Changing console.log statements to Winston log calls.
> SHOWCASE-2264 - Update log statements to Winston that were missed initially

- app/src/components/fileCache.js
- app/src/docs/v2.api-spec.yaml
- app/src/routes/v2/template.js
Add cached template hash to error response when a collision is detected
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2282
> Add template hash to error response

- app/Dockerfile
- openshift/app.bc.yaml
Update alpine-node-libreoffice to use latest tag 1.0.7
> Update alpine-node-libreoffice to 1.0.7

- app/config/default.json
- app/src/components/keycloak.js
- app/src/docs/v1.api-spec.yaml
- app/src/docs/v2.api-spec.yaml
- app/src/routes/v1/index.js
> Api gateway

- SECURITY.md
- app/package-lock.json
- app/package.json
- charts/cdogs/Chart.yaml
- charts/cdogs/README.md
This PR performs a minor version bump and releases CDOGS v2.5.0
> Release CDOGS v2.5.0

- app/app.js
- app/package-lock.json
- app/package.json
- app/src/docs/index.js
- app/src/routes/v2/index.js
- charts/cdogs/Chart.yaml
- charts/cdogs/README.md
- charts/cdogs/templates/networkpolicy.yaml
9d6a67a Add Helmet and routine npm dependency updates
341f106 Update openshift router ingress network policy
[SHOWCASE-3474](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3474)
[SHOWCASE-3498](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3498)
> Add Helmet and update openshift router ingress network policy

- Dockerfile
Updating dockerfile from Node 20.09.0-alpine to Node 20.11.1-alpine
[SHOWCASE-3494](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3494)
> Update to Node 20.11.1 LTS

- .github/CODEOWNERS
- .github/actions/build-push-container/action.yaml
- .github/actions/deploy-to-environment/action.yaml
- .github/workflows/charts-release.yaml
- .github/workflows/codeql-analysis.yaml
- .github/workflows/on-pr-closed.yaml
- .github/workflows/on-pr-opened.yaml
- .github/workflows/on-push.yaml
- .github/workflows/unit-tests.yaml
- Dockerfile
- app/package-lock.json
- app/package.json
- charts/cdogs/Chart.yaml
- charts/cdogs/README.md
- charts/cdogs/values.yaml
Update node version to 20.11.1
Update github actions
Update NPM packages
> Update node version, github actions, and NPM packages

- charts/cdogs/values.yaml
As title.
Part of regular updates to our supporting appliances.
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3628
> Update fluentbit image from 2.2.2 to 3.1.9
