bcgov/common-document-generation-service

app/app.js, app/src/components/docGen.js, app/src/components/health.js, app/src/components/utils.js, app/src/components/validators.js, app/src/routes/v1.js, app/src/routes/v1/health.js, app/tests/unit/components/utils.spec.js, app/tests/unit/components/validators/validators.customValidators.spec.js, app/tests/unit/components/validators/validators.models.spec.js
Add the filename request parameter support, use the extension of the file in the temp file Carbone processes.
Filename is now a **mandatory field.**
Also fix the health endpoint to be the correct route name.
=> Add filename support to API

openshift/app.dc.yaml
The only thing that needs k8s access is the deployer - other pods don't have any business talking to k8s
[[SHOWCASE-480]](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-480)
=> Restrict k8s API access to only deployers

openshift/app.dc.yaml
This reverts commit 9420911d10b56c6b16d7baac11368742c767bce6 and rolls back the following PR: https://github.com/bcgov/common-document-generation-service/pull/13
We have discovered that service account selectors to restrict the k8s API access do not work as documented/intended at this time. This rollback is needed to ensure that the service remains operational.
[[SHOWCASE-480]](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-480)
=> Revert "Restrict k8s API access to only deployers"

openshift/app.dc.yaml
This change re-applies https://github.com/bcgov/common-document-generation-service/pull/13 as the platform now properly parses and handles serviceaccount selectors.
* Remove unnecessary openshift annotations
=> Restrict k8s access to deployer service account

app/src/middleware/apiTracker.js
Make our timestamp pretty print field look more like Kibana's @timestamp field.
Touched up some stuff to match style guide.
The body of Kibana data has an @timestamp field, make our pretty print timestamp field look the same.
=> Pretty print Timestamp

app/app.js, app/package-lock.json, app/package.json
This PR makes it so that LibreOffice is also spun up and ready to receive file conversion requests upon API startup. This will reduce the response delay of the initial conversion.
[SHOWCASE-639](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-639)
=> Force libreoffice factory startup on API start

app/src/middleware/apiTracker.js
Adjust morgan token for outputFileType - follow logic of docGen processor.
Was returning "-" when no output type specified, but the output is actually the same as input type in that case.  Need to return something better than "-" for the dashboard.
=> Adjust morgan token for outputFileType

openshift/commonPipeline.groovy
This PR fixes the following pipeline error:
`The PersistentVolumeClaim "file-cache-data-master" is invalid: spec.resources.requests.storage: Forbidden: field can not be less than previous value`
=> Ensure pr builds use less PVC space than master builds

.github/workflows/docker-image.yaml, README.md, app/.dockerignore, app/Dockerfile, app/README.md, app/USAGE.md, app/config/default.json, app/package-lock.json, app/package.json, app/src/components/carboneCopyApi.js, openshift/README.md, openshift/app.bc.yaml
This PR focuses on emitting CDOGS as a standalone docker image that can be consumed by 3rd party developers in addition to supporting the hosted instance. Also includes comprehensive documentation update in order to cleanly present to users what they need to know to get started and working with CDOGS.
[SHOWCASE-2170](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2170)
This PR completes the lifecycle transition of docker image `doc-gen-api` to `common-document-generation-service`.
=> Add Dockerized CDOGS Support

app/src/components/carboneCopyApi.js, app/src/components/carboneRender.js, app/src/components/utils.js, app/tests/unit/components/utils.spec.js
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2094
For errors in template render that are due to supplied template syntax problems, give the user back a 422 with the message rather than a 500.
New feature (non-breaking change which adds functionality) 
Carbone just returns a string error so it could fail on either a template problem, or an actual internal server error, so just have to do a best-effort error string match.
=> Determine 422s

.github/workflows/unit-tests.yaml, app/Dockerfile, bcgovpubcode.yml, openshift/app.bc.yaml
This is a minor maintenance PR aiming at bringing CDOGS up to date with the latest node version. It also does a bit of behind the scenes maintenance by updating the test pipeline as well as adding in the bcgovpubcode manifest.
[SHOWCASE-3195](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3195)
=> Update node base image, bcgovpubcode and test pipelines

Dockerfile, app/Dockerfile
NPM appears to not propagate the SIGTERM signal to the child node app
on alpine. This is fixed by unwrapping the call and starting the app
directly instead. NPM cache directory permission issues have appeared
again for some external reason, so we need to mitigate by explicitly
forcing a permission update on the cache directory to be owned by a
non-root user.
=> Fix NPM Cache directory permission and PID Signalling bugs

.github/actions/deploy-to-environment/action.yaml
[SHOWCASE-3398](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3398)
=> Add missing namespace config value in GA Helm deploy argument command

.github/environments/values.pr.yaml, app/cacheCleaner.js, app/package.json, app/src/components/upload.js, charts/cdogs/Chart.yaml, charts/cdogs/README.md, charts/cdogs/templates/cronjob.yaml, charts/cdogs/values.yaml
This PR focuses on filling in the maintenance gap of keeping a cache directory within a specified space limit. This is important for ensuring that PVCs do not become full during the runtime of the application. It will come with the following scheduling defaults and behaviors:
- Aim to keep the PVC volume no more than 80% full
- Run twice a week (on Mondays and Thursdays)
- Iteratively delete the oldest files in the cache until the target ratio is achieved
Commits:
- 0a6b2a5 Add optional cache cleaner cronJob support to Helm chart
- 356cde2 Update Kinesis Stream default endpoint
- c5bc7f5 Implement cacheCleaner utility script to drop old cache objects
- ea6a2ea Set transient files to always leverage OS temp directory
[SHOWCASE-3332](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3332) …
=> Implement support for automated cache pruning maintenance

app/cacheCleaner.js, charts/cdogs/Chart.yaml, charts/cdogs/README.md, charts/cdogs/templates/cronjob.yaml
This PR focuses on removing unnecessary I/O from the cache cleaning cron job, instead only calculating what must be done once. We also increase the cronJob timeout from 5 to 10 minutes to make sure there is enough time for the task to succeed.
- 3dd8720 Increase cacheCleaner cronjob deadline to 10 minutes
- a78e4d3 Refactor cacheCleaner to only compute size once
[SHOWCASE-3332](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3332)
=> Optimize and remove unnecessary I/O operations from cache cleaning job

app/README.md, app/src/components/keycloak.js
ticket: https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3471
- update readme with correct template cache default
- update keycloak component so keycloak config is all optional (dependednt on whether keycloak is enabled)
=> Make Keycloak config optional and update docs

app/cacheCleaner.js, app/src/components/fileCache.js, app/src/routes/v2/template.js
Attempt to handle a race condition during copying template from temp directory to the file cache
Ticket: https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3693
- await the completion of writing template to temp directory before progressing to move the file.
- simplified code to define a temp file name
- added some minor code comments
- [x I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
=> Await writing template to temp directory

.github/CODEOWNERS, Dockerfile, app/package-lock.json, app/package.json
* Update npm dependencies
* Update Node to latest LTS version as of writing (v20.15.1)
* Update CODEOWNERS file to reflect change in team members
The [`alpine-node-libreoffice`](https://github.com/bcgov/alpine-node-libreoffice) image was also updated separately to enable the Node update in here
* See https://github.com/bcgov/alpine-node-libreoffice/pull/13
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3619
`eslint` is out of date, but it was not updated as part of this PR.
Linter rules are currently defined inside `package.json` - this is no longer the default behaviour as of v9.0.0 (it can be reverted by setting the environment variable `ESLINT_USE_FLAT_CONFIG` to `true` though) and will be removed entirely in v10.0.0. …
=> Security updates: Node v20.15.1 and npm dependencies

app/src/components/carboneCopyApi.js, app/src/components/fileCache.js
when a high frequency of requests hit the app,
template files are not managed consistently.
fileCache.find should handle when more than one template is found.
=> Improve template file handling

.github/actions/deploy-to-environment/action.yaml, .github/workflows/on-pr-closed.yaml
This adds an additional GitHub Actions step for installing `oc`.
The `ubuntu-latest` GitHub Actions image no longer includes `oc` out of the box, so it must now be explicitly installed.
*More info:* https://github.com/actions/runner-images/issues/10636
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3816
N/A
=> GHA: explicitly install oc first
